name: release
on:
  release:
    types: [published, created, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ls -a via OPEN SSH Private Key
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd ${{ secrets.BASEPATH }}/rel.pknw1.co.uk && git pull
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
