name: release
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ls -a via OPEN SSH Private Key
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd ${{ secrets.BASEPATH }}/rel.pknw1.co.uk && git pull
          host: ${{ secrets.HOST }}
          port: ${{ secrets.KS2_PORT }}
          username: ${{ secrets.KS2_USER }}
          privateKey: ${{ secrets.KS2_PRIVATE_KEY}}
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');
      - name: Echo
        run: echo ${{ steps.tag.outputs.result }}
