name: release
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Release Pull
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd ${{ secrets.BASEPATH }} && cp -R beta.pknw1.co.uk releases-pknw1.co.uk/release-$(date +%d%m%y%H%M) && ln -s releases-pknw1.co.uk/release-$(date +%d%m%y%H%M) www.pknw1.co.uk #rel.pknw1.co.uk && git pull
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          privateKey: ${{ secrets.PRIVATE_KEY}}

